import type { CommandCoverageEntry } from "./types.js";

export const COMMAND_COVERAGE_MANIFEST_VERSION = 1;

export const COMMAND_COVERAGE: readonly CommandCoverageEntry[] = [
  {
    command: "git status",
    ecosystem: "git",
    status: "experimental",
    router: "recommend",
    parser: "git-status",
    autoRewriteEligible: true,
    supportsJsonFirst: false,
    dangerLevel: "low",
    knownFlagConflicts: ["--porcelain=v2", "-z"],
    fixtures: ["clean", "dirty", "untracked", "ahead-behind", "huge"],
  },
  {
    command: "git diff",
    ecosystem: "git",
    status: "experimental",
    router: "recommend",
    parser: "git-diff",
    autoRewriteEligible: false,
    supportsJsonFirst: false,
    dangerLevel: "low",
    knownFlagConflicts: ["--binary", "--ext-diff", "--word-diff"],
    fixtures: ["small", "huge", "binary", "renames", "ansi"],
  },
  {
    command: "git log",
    ecosystem: "git",
    status: "experimental",
    router: "recommend",
    parser: "git-log",
    autoRewriteEligible: true,
    supportsJsonFirst: false,
    dangerLevel: "low",
    knownFlagConflicts: ["--format=%B", "--patch", "-p"],
    fixtures: ["oneline", "pretty", "huge", "ansi"],
  },
  {
    command: "ls/find/tree",
    ecosystem: "file",
    status: "experimental",
    router: "recommend",
    parser: "file-list",
    autoRewriteEligible: true,
    supportsJsonFirst: false,
    dangerLevel: "low",
    knownFlagConflicts: ["-exec", "-delete", "-ok"],
    fixtures: ["small", "huge", "nested", "unicode"],
  },
  {
    command: "rg",
    ecosystem: "search",
    status: "experimental",
    router: "recommend",
    parser: "rg",
    autoRewriteEligible: true,
    supportsJsonFirst: true,
    dangerLevel: "low",
    knownFlagConflicts: ["--json", "--files", "--count", "--passthru"],
    fixtures: ["empty", "many-files", "unicode", "huge", "json"],
  },
  {
    command: "grep",
    ecosystem: "search",
    status: "experimental",
    router: "recommend",
    parser: "grep",
    autoRewriteEligible: true,
    supportsJsonFirst: false,
    dangerLevel: "low",
    knownFlagConflicts: ["-z", "--binary-files", "--line-buffered"],
    fixtures: ["empty", "many-files", "binary", "huge"],
  },
  {
    command: "cat",
    ecosystem: "file",
    status: "experimental",
    router: "recommend",
    parser: "ctx-read",
    autoRewriteEligible: false,
    supportsJsonFirst: false,
    dangerLevel: "medium",
    knownFlagConflicts: ["-", "/dev/stdin"],
    fixtures: ["small", "large", "binary", "minified", "secret"],
  },
  {
    command: "pnpm test",
    ecosystem: "node",
    status: "experimental",
    router: "recommend",
    parser: "vitest-or-generic-test",
    autoRewriteEligible: false,
    supportsJsonFirst: true,
    dangerLevel: "low",
    knownFlagConflicts: ["--watch", "--ui", "--reporter"],
    fixtures: ["success", "failure", "empty", "huge", "ansi", "malformed"],
  },
  {
    command: "vitest",
    ecosystem: "node",
    status: "experimental",
    router: "recommend",
    parser: "vitest",
    autoRewriteEligible: false,
    supportsJsonFirst: true,
    dangerLevel: "low",
    knownFlagConflicts: ["--watch", "--ui", "--reporter"],
    fixtures: ["success", "failure", "empty", "huge", "ansi", "malformed"],
  },
  {
    command: "playwright test",
    ecosystem: "node",
    status: "experimental",
    router: "recommend",
    parser: "playwright",
    autoRewriteEligible: false,
    supportsJsonFirst: true,
    dangerLevel: "low",
    knownFlagConflicts: ["--debug", "--headed", "--ui"],
    fixtures: ["success", "failure", "empty", "huge", "ansi", "malformed"],
  },
  {
    command: "npm test",
    ecosystem: "node",
    status: "experimental",
    router: "recommend",
    parser: "npm",
    autoRewriteEligible: false,
    supportsJsonFirst: true,
    dangerLevel: "low",
    knownFlagConflicts: ["--watch", "--ui", "--reporter"],
    fixtures: ["success", "failure", "empty", "huge", "ansi", "malformed"],
  },
  {
    command: "npm run build",
    ecosystem: "node",
    status: "experimental",
    router: "recommend",
    parser: "npm",
    autoRewriteEligible: false,
    supportsJsonFirst: false,
    dangerLevel: "low",
    knownFlagConflicts: ["--watch"],
    fixtures: ["success", "failure", "empty", "huge", "ansi", "malformed"],
  },
  {
    command: "npm run lint",
    ecosystem: "node",
    status: "experimental",
    router: "recommend",
    parser: "eslint",
    autoRewriteEligible: false,
    supportsJsonFirst: false,
    dangerLevel: "low",
    knownFlagConflicts: ["--watch", "--fix"],
    fixtures: ["success", "failure", "empty", "huge", "ansi", "malformed"],
  },
  {
    command: "npx tsc",
    ecosystem: "node",
    status: "experimental",
    router: "recommend",
    parser: "tsc",
    autoRewriteEligible: false,
    supportsJsonFirst: false,
    dangerLevel: "low",
    knownFlagConflicts: ["--watch", "-w"],
    fixtures: ["success", "failure", "empty", "huge", "ansi", "malformed"],
  },
  {
    command: "npm run dev",
    ecosystem: "node",
    status: "experimental",
    router: "recommend",
    parser: "generic-failure",
    autoRewriteEligible: false,
    supportsJsonFirst: false,
    dangerLevel: "low",
    knownFlagConflicts: [],
    fixtures: ["startup", "port-in-use", "empty", "huge", "ansi"],
  },
  {
    command: "pytest",
    ecosystem: "python",
    status: "experimental",
    router: "recommend",
    parser: "pytest",
    autoRewriteEligible: false,
    supportsJsonFirst: true,
    dangerLevel: "low",
    knownFlagConflicts: ["-f", "--looponfail", "--pdb", "-s"],
    fixtures: ["success", "failure", "empty", "huge", "ansi", "malformed"],
  },
  {
    command: "cargo test",
    ecosystem: "rust",
    status: "experimental",
    router: "recommend",
    parser: "cargo",
    autoRewriteEligible: false,
    supportsJsonFirst: true,
    dangerLevel: "low",
    knownFlagConflicts: ["--watch", "--nocapture"],
    fixtures: ["success", "failure", "empty", "huge", "ansi", "malformed"],
  },
  {
    command: "cargo check",
    ecosystem: "rust",
    status: "experimental",
    router: "recommend",
    parser: "cargo",
    autoRewriteEligible: false,
    supportsJsonFirst: true,
    dangerLevel: "low",
    knownFlagConflicts: ["--watch"],
    fixtures: ["success", "failure", "empty", "huge", "ansi", "malformed"],
  },
  {
    command: "pip install",
    ecosystem: "python",
    status: "experimental",
    router: "recommend",
    parser: "pip",
    autoRewriteEligible: false,
    supportsJsonFirst: false,
    dangerLevel: "low",
    knownFlagConflicts: [],
    fixtures: ["success", "failure", "empty", "huge", "ansi"],
  },
  {
    command: "graphify",
    ecosystem: "graphify",
    status: "experimental",
    router: "recommend",
    parser: "generic-failure",
    autoRewriteEligible: false,
    supportsJsonFirst: false,
    dangerLevel: "low",
    knownFlagConflicts: ["--watch"],
    fixtures: ["query", "update", "path", "huge", "ansi"],
  },
  {
    command: "openclaw status",
    ecosystem: "openclaw",
    status: "experimental",
    router: "recommend",
    parser: "generic-failure",
    autoRewriteEligible: false,
    supportsJsonFirst: false,
    dangerLevel: "low",
    knownFlagConflicts: ["--watch", "--follow", "-f"],
    fixtures: ["status", "logs", "huge", "ansi", "timeout"],
  },
  {
    command: "docker logs",
    ecosystem: "docker",
    status: "experimental",
    router: "recommend",
    parser: "docker-logs",
    autoRewriteEligible: false,
    supportsJsonFirst: false,
    dangerLevel: "medium",
    knownFlagConflicts: ["-f", "--follow", "--tail=0"],
    fixtures: ["small", "huge", "follow", "ansi", "binary"],
  },
  {
    command: "gh",
    ecosystem: "github",
    status: "experimental",
    router: "recommend",
    parser: "gh",
    autoRewriteEligible: false,
    supportsJsonFirst: true,
    dangerLevel: "low",
    knownFlagConflicts: ["--web", "--interactive", "-i"],
    fixtures: ["pr-checks-json", "run-list-json", "text-failure", "huge", "ansi"],
  },
  {
    command: "curl",
    ecosystem: "network",
    status: "disabled",
    router: "recommend",
    parser: "fetch-policy",
    autoRewriteEligible: false,
    supportsJsonFirst: false,
    dangerLevel: "high",
    knownFlagConflicts: ["-d", "--data", "-H", "--header", "-u", "--user", "-k", "--insecure"],
    fixtures: ["safe-url", "credentialed-url", "redirect", "private-ip", "headers"],
  },
  {
    command: "wget",
    ecosystem: "network",
    status: "disabled",
    router: "recommend",
    parser: "fetch-policy",
    autoRewriteEligible: false,
    supportsJsonFirst: false,
    dangerLevel: "high",
    knownFlagConflicts: ["--post-data", "--post-file", "--header", "--user", "--password", "--no-check-certificate"],
    fixtures: ["safe-url", "credentialed-url", "redirect", "private-ip", "headers"],
  },
];

export function findCoverageEntry(command: string): CommandCoverageEntry | undefined {
  const normalized = command.trim().toLowerCase();
  return COMMAND_COVERAGE.find((entry) => normalized.startsWith(entry.command));
}
